---
title: "Plotly"
output: 
  html_document:
    code_folding: hide
    toc: true
    toc_float: true
---

```{r, message = FALSE}
library(dplyr)
library(tidyverse)
library(plotly)
library(viridis)
library(p8105.datasets)
```

```{r, message = FALSE}
data("ny_noaa")
```

```{r, message = FALSE}
ny_noaa$tmax <- as.numeric(ny_noaa$tmax)
ny_noaa$tmin <- as.numeric(ny_noaa$tmin)
ny_noaa$prcp <- as.numeric(ny_noaa$prcp)
ny_noaa$date <- as.character(ny_noaa$date)

ny_noaa$tmax <- ny_noaa$tmax / 10
ny_noaa$tmin <- ny_noaa$tmin / 10
ny_noaa$prcp <- ny_noaa$prcp / 10


set.seed(1)
ny_noaa =
  ny_noaa %>%
  select(ID = id, date, Precipitation = prcp, Snow = snow, SnowDepth = snwd, tmax, tmin) %>%
  filter(
    !is.na(Precipitation),
    !is.na(Snow),
    !is.na(SnowDepth),
    !is.na(tmax),
    !is.na(tmin)) %>%
  sample_n(1000)

ny_noaa %>%
  count(ID) %>%
  mutate(ID = fct_reorder(ID, n)) %>%
  plot_ly(x = ~ID, y = ~n, color = ~ID, type = "bar")

ny_noaa %>%
  mutate(text_label = str_c("ID: ", ID, '\nPrecipitation: ', Precipitation)) %>%
  plot_ly(
    x = ~date, y = ~Precipitation, type = "scatter", mode = "markers",
    color = ~Precipitation, text = ~text_label, alpha = 0.5)

ny_noaa %>%
  mutate(text_label = str_c("ID: ", ID, '\nSnow: ', Snow)) %>%
  plot_ly(
    x = ~date, y = ~Snow, type = "scatter", mode = "markers",
    color = ~Snow, text = ~text_label, alpha = 0.5)


common_ID =
  ny_noaa %>%
  count(ID, sort = TRUE) %>%
  top_n(8) %>%
  select(ID)
  
inner_join(ny_noaa, common_ID) %>%
  mutate(ID = fct_reorder(ID, tmax)) %>%
  plot_ly(y = ~tmax, color = ~ID, type = "box")

inner_join(ny_noaa, common_ID) %>%
  mutate(ID = fct_reorder(ID, tmin)) %>%
  plot_ly(y = ~tmin, color = ~ID, type = "box")

```

